name: QA
on: push
jobs:
  qa:
    name: Run QA checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: WHERE THE F AM I
        uses: matthewrmshin/conda-action@v1.1
        with:
          args: ls
      - name: Update Conda environment
        uses: matthewrmshin/conda-action@v1.1
        with:
          args: conda env update
      - name: Run QA steps
        uses: matthewrmshin/conda-action@v1.1
        with:
          args: PYTHONPATH=./python/de/cli.py qa
